name: Knowledge Applications Settings Exporter
description: Fetch all application settings from knowledge
inputs:
  app:
    description: The name of the application to fetch settings for
    required: true
  clone_token:
    description: The Github token to use for cloning
    required: true
branding:
  icon: 'lock'
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
