name: Continuous Integration Preparation
description: Setup the virtual environment we run in
inputs:
  settings:
    description: The name of the application to fetch settings for
    required: false
  target:
    description: The name of the target to run
    required: true
  clone_token:
    description: The Github token to use for cloning
    required: true
  settings_secret_key:
    description: When settings should be loaded,
      we require the secret key for decryption
    required: false
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'composite'
  steps:
    # Checkout the application code to the current working directory
    - uses: actions/checkout@v4

    # Run our CI preparations
    - run: node dist/index.js
      shell: bash
      working-directory: '${{ github.action_path }}'
      env:
        INPUT_SETTINGS: '${{ inputs.settings }}'
        INPUT_TARGET: '${{ inputs.target }}'
        INPUT_CLONE_TOKEN: '${{ inputs.clone_token }}'
        INPUT_SETTINGS_SECRET_KEY: '${{ inputs.settings_secret_key }}'
