name: Application Tests in a single job

on:
  workflow_call:
    inputs:
      targets:
        description: 'The GNU Make targets to run in a single job'
        required: false
        # The root test targets are: specs, style, security
        # Just deliver the GNU Make recipe suffix without leading `test-`.
        # By default (without specific caller configuration) we run the `test`
        # GNU Make recipe. This way the application Makefile defines what to
        # run by default. To configure multiple targets use comma as
        # separator. (eg. `security,style,specs`)
        default: 'test'
        type: string

jobs:
  test:
    name: Application
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Prepare the environment
        uses: hausgold/actions/ci@v2
        with:
          clone_token: '${{ secrets.CLONE_TOKEN }}'
          settings_secret_key: '${{ secrets.SETTINGS_SECRET_KEY }}'
          settings: '${{ github.repository }}'
          target: ci/docker-app

      - name: Install the application
        run: make install

      - name: Run the application tests
        run: make $(echo '${{ inputs.targets }}' | sed
          -e 's/^/test-/g' -e 's/,/ test-/g' -e 's/test-test/test/g')

      - name: Upload the code coverage report
        run: coverage

      - name: Build and upload application documentation
        run: test -d build/docs &&
          make -C build/docs upload notify &&
          coverage --docs-only
        if: github.ref == 'refs/heads/master'
        env:
          WORKFLOW_DISPATCH_TOKEN: '${{ secrets.WORKFLOW_DISPATCH_TOKEN }}'
